/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import controller.ControllerJoinProdutoEndVendaProduto;
import controller.ControllerProduto;
import controller.ControllerVenda;
import controller.ControllerVendaCliente;
import controller.ControllerVendaProduto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelCliente;
import model.ModelJoinProdutoEndVendaProduto;
import model.ModelProduto;
import model.ModelVenda;
import model.ModelVendaCliente;
import model.ModelVendaProduto;
import util.BLDatas;

/**
 *
 * @author Joshua
 */
public class ViewVenda extends javax.swing.JFrame {

    //ControllerCliente controllerCliente = new ControllerCliente();
    ControllerCliente controllerCliente = new ControllerCliente();
    ControllerVenda controllerVenda = new ControllerVenda();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelCliente = new ArrayList<>();

    ControllerProduto controllerProduto = new ControllerProduto();
    ModelProduto modelProduto = new ModelProduto();
    ArrayList<ModelProduto> listaModelProduto = new ArrayList<>();
    ArrayList<ModelVendaCliente> listaModelVendaCliente = new ArrayList<>();
    ControllerVendaCliente controllerVendaCliente = new ControllerVendaCliente();
    //ModelVenda modelVenda = new ModelVenda();
    ModelVenda modelVenda = new ModelVenda();
    BLDatas bLDatas = new BLDatas();
    ControllerVendaProduto controllerVendaProduto = new ControllerVendaProduto();
    ModelVendaProduto modelVendaProduto = new ModelVendaProduto();
    ArrayList<ModelVendaProduto> listaModelVendaProduto = new ArrayList<>();
    ControllerJoinProdutoEndVendaProduto controllerJoinProdutoEndVendaProduto = new ControllerJoinProdutoEndVendaProduto();
    ModelJoinProdutoEndVendaProduto modelJoinProdutoEndVendaProduto = new ModelJoinProdutoEndVendaProduto();
    ArrayList<ModelJoinProdutoEndVendaProduto> listaJoinProdutoEndVendaProduto = new ArrayList<>();
    String alterarSalvar;

    /**
     * Creates new form ViewVenda
     */
    public ViewVenda() {
        //setLocationRelativeTo(null);
        initComponents();
        setLocationRelativeTo(null);
        listarCliente();
        listarProduto();
        carregarVendaCliente();
        preencherCodigoClientePeloComboBox();
        preencherCodigoProdutoPeloComboBox();
        limparDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tableCadastro = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txt_CodigoCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_IdVenda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_CodigoProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Quantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_Adicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowProdutoVenda = new javax.swing.JTable();
        btn_Salvar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Novo = new javax.swing.JButton();
        txt_ValorTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Desconto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_remover_produto = new javax.swing.JButton();
        txt_NomeProduto = new componentes.UJComboBox();
        txt_NomeCliente = new componentes.UJComboBox();
        jPanel3 = new javax.swing.JPanel();
        txtPesquisaVenda = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_pesuisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbShowVenda = new javax.swing.JTable();
        btn_Excluir = new javax.swing.JButton();
        btn_Alterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(71, 120, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Vendas NC");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        txt_CodigoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CodigoClienteFocusLost(evt);
            }
        });

        jLabel1.setText("Código do Cliente");

        jLabel2.setText("Nome do Cliente");

        txt_IdVenda.setBackground(new java.awt.Color(204, 255, 204));
        txt_IdVenda.setBorder(null);

        jLabel3.setText("ID da Venda");

        txt_CodigoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CodigoProdutoFocusLost(evt);
            }
        });

        jLabel4.setText("Código do Produto");

        jLabel5.setText("Produto");

        jLabel6.setText("Quantidade");

        btn_Adicionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Adicionar.setForeground(new java.awt.Color(0, 204, 51));
        btn_Adicionar.setText("ADD");
        btn_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdicionarActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tbShowProdutoVenda.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbShowProdutoVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Produto", "Produto", "Quantidade", "Preço Unitário", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbShowProdutoVenda.setGridColor(new java.awt.Color(255, 255, 255));
        tbShowProdutoVenda.setRowHeight(22);
        jScrollPane1.setViewportView(tbShowProdutoVenda);
        if (tbShowProdutoVenda.getColumnModel().getColumnCount() > 0) {
            tbShowProdutoVenda.getColumnModel().getColumn(0).setMinWidth(110);
            tbShowProdutoVenda.getColumnModel().getColumn(0).setPreferredWidth(110);
            tbShowProdutoVenda.getColumnModel().getColumn(0).setMaxWidth(110);
            tbShowProdutoVenda.getColumnModel().getColumn(2).setMinWidth(110);
            tbShowProdutoVenda.getColumnModel().getColumn(2).setPreferredWidth(110);
            tbShowProdutoVenda.getColumnModel().getColumn(2).setMaxWidth(110);
            tbShowProdutoVenda.getColumnModel().getColumn(3).setMinWidth(90);
            tbShowProdutoVenda.getColumnModel().getColumn(3).setPreferredWidth(90);
            tbShowProdutoVenda.getColumnModel().getColumn(3).setMaxWidth(90);
            tbShowProdutoVenda.getColumnModel().getColumn(3).setHeaderValue("Preço Unitário");
            tbShowProdutoVenda.getColumnModel().getColumn(4).setMinWidth(90);
            tbShowProdutoVenda.getColumnModel().getColumn(4).setPreferredWidth(90);
            tbShowProdutoVenda.getColumnModel().getColumn(4).setMaxWidth(90);
            tbShowProdutoVenda.getColumnModel().getColumn(4).setHeaderValue("Valor Total");
        }

        btn_Salvar.setText("Salvar");
        btn_Salvar.setEnabled(false);
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");

        btn_Novo.setText("Novo");
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });

        txt_ValorTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setText("Valor Total:");

        txt_Desconto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Desconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DescontoFocusLost(evt);
            }
        });

        jLabel8.setText("Desconto");

        btn_remover_produto.setText("Remover Produto");
        btn_remover_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remover_produtoActionPerformed(evt);
            }
        });

        txt_NomeProduto.setAutocompletar(true);
        txt_NomeProduto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                txt_NomeProdutoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        txt_NomeCliente.setAutocompletar(true);
        txt_NomeCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                txt_NomeClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_CodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_IdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_CodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txt_NomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_remover_produto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_IdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_CodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_CodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Salvar)
                    .addComponent(btn_Cancelar)
                    .addComponent(btn_Novo)
                    .addComponent(btn_remover_produto))
                .addContainerGap())
        );

        tableCadastro.addTab("Cadastro", jPanel2);

        jLabel10.setText("Pesquisa:");

        btn_pesuisar.setText("Pesquisar");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tbShowVenda.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbShowVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do Cliente", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbShowVenda.setGridColor(new java.awt.Color(255, 255, 255));
        tbShowVenda.setRowHeight(22);
        jScrollPane2.setViewportView(tbShowVenda);
        if (tbShowVenda.getColumnModel().getColumnCount() > 0) {
            tbShowVenda.getColumnModel().getColumn(0).setMinWidth(110);
            tbShowVenda.getColumnModel().getColumn(0).setPreferredWidth(110);
            tbShowVenda.getColumnModel().getColumn(0).setMaxWidth(110);
            tbShowVenda.getColumnModel().getColumn(2).setMinWidth(110);
            tbShowVenda.getColumnModel().getColumn(2).setPreferredWidth(110);
            tbShowVenda.getColumnModel().getColumn(2).setMaxWidth(110);
        }

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        btn_Alterar.setText("Alterar");
        btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtPesquisaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pesuisar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jScrollPane2)
                    .addGap(9, 9, 9)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pesuisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Excluir)
                    .addComponent(btn_Alterar))
                .addGap(19, 19, 19))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        tableCadastro.addTab("Consultar/Excluir/Alterar", jPanel3);

        getContentPane().add(tableCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_CodigoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CodigoClienteFocusLost
        // TODO add your handling code here:
        modelCliente = controllerCliente.retornarClienteController(Integer.parseInt(this.txt_CodigoCliente.getText()));
        this.txt_NomeCliente.setSelectedItem(modelCliente.getNome());
    }//GEN-LAST:event_txt_CodigoClienteFocusLost

    private void txt_CodigoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CodigoProdutoFocusLost
        // TODO add your handling code here:
        modelProduto = controllerProduto.retornarProdutoController(Integer.parseInt(this.txt_CodigoProduto.getText()));
        this.txt_NomeProduto.setSelectedItem(modelProduto.getProduto());
    }//GEN-LAST:event_txt_CodigoProdutoFocusLost

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        // TODO add your handling code here:
        int linha = this.tbShowVenda.getSelectedRow();
        int idVenda = (int) this.tbShowVenda.getValueAt(linha, 0);

        /**
         * ESCLUINDO E SOMANDO O RSTOQUE
         */
        listaModelProduto = new ArrayList<>();
        listaJoinProdutoEndVendaProduto = controllerJoinProdutoEndVendaProduto.getListaJoinProdutoEndVendaProdutoController(idVenda);

        for (int i = 0; i < listaJoinProdutoEndVendaProduto.size(); i++) {
            modelProduto = new ModelProduto();
            modelProduto.setIdProduto(listaJoinProdutoEndVendaProduto.get(i).getModelProduto().getIdProduto());
            modelProduto.setEstoque(
                    listaJoinProdutoEndVendaProduto.get(i).getModelProduto().getEstoque()
                    + listaJoinProdutoEndVendaProduto.get(i).getModelVendaProduto().getQtd_produto()
            );
            listaModelProduto.add(modelProduto);
        } // FIM EXCLUSÃO E SOMA DO ESTOQUE
        if (controllerProduto.alterarEstoqueProdutoController(listaModelProduto)) {
            controllerVendaProduto.excluirVendaProdutoController(idVenda);
            if (controllerVenda.excluirVendaController(idVenda)) {
                JOptionPane.showMessageDialog(this, "Venda excluida com sucesso",
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                carregarVendaCliente();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir Venda",
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir Venda",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdicionarActionPerformed
        // TODO add your handling code here:
        if (this.txt_Quantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Você deve preencher todos os campos", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            modelProduto = controllerProduto.retornarProdutoController(Integer.parseInt(this.txt_CodigoProduto.getText()));

            DefaultTableModel table = (DefaultTableModel) tbShowProdutoVenda.getModel();
            int cont = 0;
            double quantidade = 0;
            quantidade = Double.parseDouble(this.txt_Quantidade.getText());
            for (int i = 0; i < cont; i++) {
                table.setNumRows(0);
            }

            table.addRow(new Object[]{
                modelProduto.getIdProduto(),
                modelProduto.getProduto(),
                this.txt_Quantidade.getText(),
                modelProduto.getPreco(),
                quantidade * modelProduto.getPreco()
            });
            somarValorTotalProduto();
        }
    }//GEN-LAST:event_btn_AdicionarActionPerformed

    private void txt_DescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DescontoFocusLost
        // TODO add your handling code here:
        somarValorTotalProduto();
    }//GEN-LAST:event_txt_DescontoFocusLost

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
        // TODO add your handling code here:
        alterarSalvar = "salvar";
        limparDados();
        this.btn_Salvar.setEnabled(true);
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        // TODO add your handling code here:

        int codigoVenda = 0;
        double desconto = 0;

        listaModelVendaProduto = new ArrayList<>();

        if (this.txt_Desconto.getText().equals("")) {
            desconto = 0;
        } else {
            desconto = Double.parseDouble(this.txt_Desconto.getText());
        }
        if (!this.txt_IdVenda.getText().equals("")) {
            modelVenda.setIdVenda(Integer.parseInt(this.txt_IdVenda.getText()));
        }

        modelVenda.setIdCliente(Integer.parseInt(this.txt_CodigoCliente.getText()));
        try {
            modelVenda.setData_Venda(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
            //Logger.getLogger(ViewVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelVenda.setValor_liquido(Double.parseDouble(this.txt_ValorTotal.getText()));
        modelVenda.setValor_bruto(Double.parseDouble(this.txt_ValorTotal.getText()) + desconto);
        modelVenda.setDesconto(desconto);

        /**
         * UTILIZANDO A CONDIÇÃO COM A VARIÁVEL alterarSalvar
         */
        if (alterarSalvar.equals("salvar")) {

            /**
             * SALVAR VENDA NO BANCO
             */
            codigoVenda = controllerVenda.salvarVendaController(modelVenda);
            if (codigoVenda > 0) {
                JOptionPane.showMessageDialog(this, "Venda salva com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao salvar venda", "Erro", JOptionPane.ERROR);
            }

            int cont = this.tbShowProdutoVenda.getRowCount();
            for (int i = 0; i < cont; i++) {
                int codigoProduto = (int) this.tbShowProdutoVenda.getValueAt(i, 0);
                modelVendaProduto = new ModelVendaProduto();
                modelProduto = new ModelProduto();
                modelVendaProduto.setIdProduto(codigoProduto);
                modelVendaProduto.setIdVenda(codigoVenda);
                modelVendaProduto.setPreco_produto((double) this.tbShowProdutoVenda.getValueAt(i, 3));
                modelVendaProduto.setQtd_produto(Integer.parseInt(this.tbShowProdutoVenda.getValueAt(i, 2).toString()));

                /**
                 * FAZENDO BAIXA NO ESTOQUE
                 */
                modelProduto.setIdProduto(codigoProduto);
                modelProduto.setEstoque(controllerProduto.retornarProdutoController(codigoProduto).getEstoque()
                        - Integer.parseInt(this.tbShowProdutoVenda.getValueAt(i, 2).toString()));

                listaModelVendaProduto.add(modelVendaProduto);
                listaModelProduto.add(modelProduto);
            }

            /**
             * SALVAR PRODUTOS DA VENDA
             */
            if (controllerVendaProduto.salvarVendaProdutosController(listaModelVendaProduto)) {
                /**
                 * ALTERAR O ESTOQUE DE PRODUTO
                 */
                controllerProduto.alterarEstoqueProdutoController(listaModelProduto);
//                JOptionPane.showMessageDialog(this, "Produto da Venda salvo com"
//                        + " sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                limparDados();
                carregarVendaCliente();
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao salvar Produto da "
                        + "venda", "Erro", JOptionPane.ERROR);
            }
            // FIM DO MÉTODO SALVAR
            this.btn_Salvar.setEnabled(false);
        } else {
            /// CONDIÇÃO ALTERAR
            int linha = this.tbShowVenda.getSelectedRow();
            codigoVenda = (int) this.tbShowVenda.getValueAt(linha, 0);

            /**
             * ESCLUINDO E SOMANDO O RSTOQUE
             */
            listaModelProduto = new ArrayList<>();
            listaJoinProdutoEndVendaProduto = controllerJoinProdutoEndVendaProduto.getListaJoinProdutoEndVendaProdutoController(codigoVenda);
            for (int i = 0; i < listaJoinProdutoEndVendaProduto.size(); i++) {
                modelProduto = new ModelProduto();
                modelProduto.setIdProduto(listaJoinProdutoEndVendaProduto.get(i).getModelProduto().getIdProduto());
                modelProduto.setEstoque(
                        listaJoinProdutoEndVendaProduto.get(i).getModelProduto().getEstoque()
                        + listaJoinProdutoEndVendaProduto.get(i).getModelVendaProduto().getQtd_produto()
                );
                listaModelProduto.add(modelProduto);
            } // FIM EXCLUSÃO E SOMA DO ESTOQUE
            if (controllerProduto.alterarEstoqueProdutoController(listaModelProduto)) {
                if (controllerVendaProduto.excluirVendaProdutoController(codigoVenda)) {
                    // if (controllerVenda.excluirVendaController(idVenda)) {
//                    JOptionPane.showMessageDialog(this, "Venda excluida com sucesso",
//                            "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    carregarVendaCliente();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir Venda",
                            "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir Venda",
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
            if (controllerVenda.alterarVendaController(modelVenda)) {
                JOptionPane.showMessageDialog(this, "Venda atualizada com "
                        + "sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao atualizar a venda",
                        "Erro", JOptionPane.ERROR);
            }
            
            int cont = this.tbShowProdutoVenda.getRowCount();
            for (int i = 0; i < cont; i++) {
                int codigoProduto = (int) this.tbShowProdutoVenda.getValueAt(i, 0);
                modelVendaProduto = new ModelVendaProduto();
                modelProduto = new ModelProduto();
                modelVendaProduto.setIdProduto(codigoProduto);
                modelVendaProduto.setIdVenda(codigoVenda);
                modelVendaProduto.setPreco_produto((double) this.tbShowProdutoVenda.getValueAt(i, 3));
                modelVendaProduto.setQtd_produto(Integer.parseInt(this.tbShowProdutoVenda.getValueAt(i, 2).toString()));

                /**
                 * FAZENDO BAIXA NO ESTOQUE
                 */
                modelProduto.setIdProduto(codigoProduto);
                modelProduto.setEstoque(controllerProduto.retornarProdutoController(codigoProduto).getEstoque()
                        - Integer.parseInt(this.tbShowProdutoVenda.getValueAt(i, 2).toString()));

                listaModelVendaProduto.add(modelVendaProduto);
                listaModelProduto.add(modelProduto);
            }
            
            /**
             * SALVAR PRODUTOS DA VENDA
             */
            if (controllerVendaProduto.salvarVendaProdutosController(listaModelVendaProduto)) {
//                JOptionPane.showMessageDialog(this, "Produto da Venda salvo com"
//                        + " sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                limparDados();
                carregarVendaCliente();
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao salvar Produto da "
                        + "venda", "Erro", JOptionPane.ERROR);
            }
        }
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterarActionPerformed
        // TODO add your handling code here:
        alterarSalvar = "salvar";
        alterarSalvar = "alterar";
        int linha = tbShowVenda.getSelectedRow();
        int idVenda = (int) tbShowVenda.getValueAt(linha, 0);
        listaJoinProdutoEndVendaProduto = controllerJoinProdutoEndVendaProduto.getListaJoinProdutoEndVendaProdutoController(idVenda);
        DefaultTableModel table = (DefaultTableModel) tbShowProdutoVenda.getModel();
        table.setNumRows(0);
        for (int i = 0; i < listaJoinProdutoEndVendaProduto.size(); i++) {
            this.txt_IdVenda.setText(String.valueOf(listaJoinProdutoEndVendaProduto.get(i).getModelVendaProduto().getIdVenda()));
            table.addRow(new Object[]{
                listaJoinProdutoEndVendaProduto.get(i).getModelProduto().getIdProduto(),
                listaJoinProdutoEndVendaProduto.get(i).getModelProduto().getProduto(),
                listaJoinProdutoEndVendaProduto.get(i).getModelVendaProduto().getQtd_produto(),
                listaJoinProdutoEndVendaProduto.get(i).getModelVendaProduto().getPreco_produto(),
                listaJoinProdutoEndVendaProduto.get(i).getModelVendaProduto().getQtd_produto()
                * listaJoinProdutoEndVendaProduto.get(i).getModelVendaProduto().getPreco_produto(),});
        }
        somarValorTotalProduto();
        this.tableCadastro.setSelectedIndex(0);
    }//GEN-LAST:event_btn_AlterarActionPerformed

    private void btn_remover_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remover_produtoActionPerformed
        // TODO add your handling code here:
        int linha = tbShowProdutoVenda.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel) tbShowProdutoVenda.getModel();
        table.removeRow(linha);
        somarValorTotalProduto();
    }//GEN-LAST:event_btn_remover_produtoActionPerformed

    private void txt_NomeProdutoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_txt_NomeProdutoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (txt_NomeProduto.isPopupVisible()) {
            preencherCodigoProdutoPeloComboBox();
        }
    }//GEN-LAST:event_txt_NomeProdutoPopupMenuWillBecomeInvisible

    private void txt_NomeClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_txt_NomeClientePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (txt_NomeCliente.isPopupVisible()) {
            preencherCodigoClientePeloComboBox();
        }
    }//GEN-LAST:event_txt_NomeClientePopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVenda().setVisible(true);
            }
        });
    }

    private void preencherCodigoClientePeloComboBox() {
        modelCliente = controllerCliente.retornarClienteController(txt_NomeCliente.getSelectedItem().toString());
        this.txt_CodigoCliente.setText(modelCliente.getIdCliente() + "");
    }

    private void preencherCodigoProdutoPeloComboBox() {
        modelProduto = controllerProduto.retornarProdutoController(txt_NomeProduto.getSelectedItem().toString());
        this.txt_CodigoProduto.setText(modelProduto.getIdProduto() + "");
    }

    private void listarCliente() {
        listaModelCliente = controllerCliente.retornarListaClienteController();
        this.txt_NomeCliente.removeAllItems();
        for (int i = 0; i < listaModelCliente.size(); i++) {
            this.txt_NomeCliente.addItem(listaModelCliente.get(i).getNome());
        }
    }

    private void listarProduto() {
        listaModelProduto = controllerProduto.retornarListaProdutoController();
        this.txt_NomeProduto.removeAllItems();
        for (int i = 0; i < listaModelProduto.size(); i++) {
            this.txt_NomeProduto.addItem(listaModelProduto.get(i).getProduto());
        }
    }

    private void somarValorTotalProduto() {
        double soma = 0, valor;
        int cont = this.tbShowProdutoVenda.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = (double) this.tbShowProdutoVenda.getValueAt(i, 4);
            soma += valor;
        }
        this.txt_ValorTotal.setText(String.valueOf(soma));
        descontoValor();
    }

    private void descontoValor() {
        try {
            this.txt_ValorTotal.setText(String.valueOf(
                    Double.parseDouble(this.txt_ValorTotal.getText()) - Double.parseDouble(this.txt_Desconto.getText())));
        } catch (NumberFormatException e) {
        }
    }

    private void carregarVendaCliente() {
        DefaultTableModel table = (DefaultTableModel) tbShowVenda.getModel();
        listaModelVendaCliente = controllerVendaCliente.getListaVendaClienteController();
        int cont = listaModelVendaCliente.size();
        table.setNumRows(0);
        for (int i = 0; i < cont; i++) {
            table.addRow(new Object[]{
                listaModelVendaCliente.get(i).getModelVenda().getIdVenda(),
                listaModelVendaCliente.get(i).getModelCliente().getNome(),
                listaModelVendaCliente.get(i).getModelVenda().getData_Venda()
            });
        }
    }

    private void limparDados() {
        this.txt_Quantidade.setText("");
        this.txt_ValorTotal.setText("");
        this.txt_Desconto.setText("");
        DefaultTableModel table = (DefaultTableModel) tbShowProdutoVenda.getModel();
        table.setNumRows(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Adicionar;
    private javax.swing.JButton btn_Alterar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JButton btn_pesuisar;
    private javax.swing.JButton btn_remover_produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tableCadastro;
    private javax.swing.JTable tbShowProdutoVenda;
    private javax.swing.JTable tbShowVenda;
    private javax.swing.JTextField txtPesquisaVenda;
    private javax.swing.JTextField txt_CodigoCliente;
    private javax.swing.JTextField txt_CodigoProduto;
    private javax.swing.JTextField txt_Desconto;
    private javax.swing.JTextField txt_IdVenda;
    private componentes.UJComboBox txt_NomeCliente;
    private componentes.UJComboBox txt_NomeProduto;
    private javax.swing.JTextField txt_Quantidade;
    private javax.swing.JTextField txt_ValorTotal;
    // End of variables declaration//GEN-END:variables
}
