/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerUsuario;
import interfaces.MetodosGerais;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelUsuario;

/**
 *
 * @author Joshua
 */
public class ViewUsuario extends javax.swing.JFrame implements MetodosGerais {

    ArrayList<ModelUsuario> listaModelUsuario = new ArrayList<>();
    ControllerUsuario controllerUsuario = new ControllerUsuario();
    ModelUsuario modelUsuario = new ModelUsuario();
    String salvarAlterar;

    /**
     * Creates new form ViewUsuario
     */
    public ViewUsuario() {
        initComponents();
        mostrarUsuario();
        setLocationRelativeTo(null);
        abilitarDesabilitar(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_Pesquisar = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSalvar = new java.awt.Button();
        btnNovo = new java.awt.Button();
        btnAtualizar = new java.awt.Button();
        btnCancelar = new java.awt.Button();
        btnEliminar = new java.awt.Button();
        txtCodigoUsuario = new javax.swing.JTextField();
        txtSenhaUsuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lblSenhaUsuario = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowUsuario = new javax.swing.JTable();
        txtNomeUsuario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblEmailUsuario = new javax.swing.JLabel();
        txtEmailUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuário");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Formulário de Usuários");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        btn_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Search_18px.png"))); // NOI18N
        btn_Pesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Pesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_PesquisarMousePressed(evt);
            }
        });
        jPanel2.add(btn_Pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        txtPesquisa.setBackground(new java.awt.Color(123, 156, 225));
        txtPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisa.setBorder(null);
        txtPesquisa.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPesquisa.setPreferredSize(new java.awt.Dimension(2, 20));
        jPanel2.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 60));

        jPanel3.setBackground(new java.awt.Color(23, 35, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        jPanel3.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sair");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 30, -1));

        btnSalvar.setBackground(new java.awt.Color(0, 204, 0));
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setLabel("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        btnNovo.setBackground(new java.awt.Color(71, 120, 197));
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setLabel("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel3.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        btnAtualizar.setBackground(new java.awt.Color(255, 153, 0));
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setLabel("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setLabel("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setLabel("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 710, 70));

        txtCodigoUsuario.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigoUsuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txtCodigoUsuario.setBorder(null);
        txtCodigoUsuario.setEnabled(false);
        jPanel1.add(txtCodigoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 210, 30));

        txtSenhaUsuario.setBackground(new java.awt.Color(204, 204, 204));
        txtSenhaUsuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txtSenhaUsuario.setBorder(null);
        jPanel1.add(txtSenhaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 210, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Senha do Usuário");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        lblSenhaUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblSenhaUsuario.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblSenhaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 210, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Email do Usuário");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tbShowUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbShowUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Usuário", "Nome do Usário", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbShowUsuario.setGridColor(new java.awt.Color(255, 255, 255));
        tbShowUsuario.setRowHeight(22);
        jScrollPane1.setViewportView(tbShowUsuario);
        if (tbShowUsuario.getColumnModel().getColumnCount() > 0) {
            tbShowUsuario.getColumnModel().getColumn(0).setMinWidth(50);
            tbShowUsuario.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbShowUsuario.getColumnModel().getColumn(1).setMinWidth(150);
            tbShowUsuario.getColumnModel().getColumn(1).setPreferredWidth(150);
            tbShowUsuario.getColumnModel().getColumn(2).setMinWidth(150);
            tbShowUsuario.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 670, 150));

        txtNomeUsuario.setBackground(new java.awt.Color(204, 204, 204));
        txtNomeUsuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txtNomeUsuario.setBorder(null);
        jPanel1.add(txtNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 210, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Nome do Usuário");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("ID do Usuário");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        lblNomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNomeUsuario.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 210, 20));

        lblEmailUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblEmailUsuario.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblEmailUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 210, 20));

        txtEmailUsuario.setBackground(new java.awt.Color(204, 204, 204));
        txtEmailUsuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txtEmailUsuario.setBorder(null);
        jPanel1.add(txtEmailUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 540));

        setBounds(0, 0, 709, 539);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        //ViewUsuario.DISPOSE_ON_CLOSE
        dispose();
    }//GEN-LAST:event_btn_exitMousePressed

    int xx, xy;
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (salvarAlterar.equals("atualizar")) {
            this.alterarUsuario();
        } else if (salvarAlterar.equals("salvar")) {
            this.salvarCliente();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        this.salvarAlterar = "atualizar";
        this.abilitarDesabilitar(true);
        int linha = this.tbShowUsuario.getSelectedRow();
        try {
            int idUsuario = (int) this.tbShowUsuario.getValueAt(linha, 0);
            modelUsuario = controllerUsuario.retornarUsuarioController(idUsuario);
            this.txtCodigoUsuario.setText(Integer.toString(modelUsuario.getIdUsuario()));
            this.txtNomeUsuario.setText(modelUsuario.getNomeUsuario());
            this.txtEmailUsuario.setText(modelUsuario.getEmailUsuario());
            this.txtSenhaUsuario.setText(modelUsuario.getSenhaUsuario());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Porfavor selecione um registo para"
                    + " atualizar", "Código inválido", JOptionPane.WARNING_MESSAGE);
            this.abilitarDesabilitar(false);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            excluirUsuario();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Porfavor selecione um registo para"
                    + " eliminar", "Código inválido", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        //new ViewCliente().setVisible(true);
        abilitarDesabilitar(true);
        limparCampos();
        salvarAlterar = "salvar";
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        abilitarDesabilitar(false);
        limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btn_PesquisarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PesquisarMousePressed
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) this.tbShowUsuario.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(table);
        this.tbShowUsuario.setRowSorter(classificador);
        String textPesquisa = this.txtPesquisa.getText();
        classificador.setRowFilter(RowFilter.regexFilter(textPesquisa, 1));
    }//GEN-LAST:event_btn_PesquisarMousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUsuario().setVisible(true);
            }
        });
    }

    private void salvarCliente() {
        if (txtNomeUsuario.getText().isEmpty() || txtSenhaUsuario.getText().isEmpty() || txtSenhaUsuario.getText().isEmpty()) {
            lblNomeUsuario.setText("Digite o Nome");
            lblEmailUsuario.setText("Digite o Email");
            lblSenhaUsuario.setText("Digite a Senha");
        } else {
            modelUsuario.setNomeUsuario(this.txtNomeUsuario.getText());
            modelUsuario.setEmailUsuario(this.txtEmailUsuario.getText());
            modelUsuario.setSenhaUsuario(this.txtSenhaUsuario.getText());
            if (controllerUsuario.salvarUsuarioController(modelUsuario) > 0) {
                JOptionPane.showMessageDialog(this, "Usuário cadastrado com "
                        + "Sucesso", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Usuário não cadastrado "
                        + "Erro!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
            lblNomeUsuario.setText("");
            lblEmailUsuario.setText("");
            lblSenhaUsuario.setText("");
            this.mostrarUsuario();
            this.limparCampos();
            this.abilitarDesabilitar(false);
        }
    }

    private void alterarUsuario() {
        modelUsuario.setNomeUsuario(this.txtNomeUsuario.getText());
        modelUsuario.setEmailUsuario(this.txtEmailUsuario.getText());
        modelUsuario.setSenhaUsuario(this.txtSenhaUsuario.getText());
        if (controllerUsuario.alterarUsuarioController(modelUsuario)) {
            JOptionPane.showMessageDialog(this, "Usuário atualizado com "
                    + "Sucesso", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Usuário não atualizado "
                    + "Erro!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        lblNomeUsuario.setText("");
        lblEmailUsuario.setText("");
        lblSenhaUsuario.setText("");
        this.mostrarUsuario();
        this.limparCampos();
        this.abilitarDesabilitar(false);
    }

    private void excluirUsuario() {
        int excluirlinha = tbShowUsuario.getSelectedRow();
        int idUsuario = (int) tbShowUsuario.getValueAt(excluirlinha, 0);
        if (controllerUsuario.excluirUsuarioController(idUsuario)) {
            JOptionPane.showMessageDialog(this, "Usuário Eliminado com "
                    + "Sucesso", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
            this.mostrarUsuario();
            this.abilitarDesabilitar(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao eliminar Usuário",
                    "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarUsuario() {
        listaModelUsuario = controllerUsuario.retornarListaUsuarioController();
        DefaultTableModel table = (DefaultTableModel) tbShowUsuario.getModel();
        table.setNumRows(0);
        int cont = listaModelUsuario.size();
        for (int i = 0; i < cont; i++) {
            table.addRow(new Object[]{
                listaModelUsuario.get(i).getIdUsuario(),
                listaModelUsuario.get(i).getNomeUsuario(),
                listaModelUsuario.get(i).getEmailUsuario(), // listaModelUsuario.get(i).getSenhaUsuario()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAtualizar;
    private java.awt.Button btnCancelar;
    private java.awt.Button btnEliminar;
    private java.awt.Button btnNovo;
    private java.awt.Button btnSalvar;
    private javax.swing.JLabel btn_Pesquisar;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmailUsuario;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblSenhaUsuario;
    private javax.swing.JTable tbShowUsuario;
    private javax.swing.JTextField txtCodigoUsuario;
    private javax.swing.JTextField txtEmailUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtSenhaUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void abilitarDesabilitar(boolean condicao) {
        txtNomeUsuario.setEnabled(condicao);
        txtEmailUsuario.setEnabled(condicao);
        txtSenhaUsuario.setEnabled(condicao);
        btnSalvar.setEnabled(condicao);
    }

    @Override
    public void limparCampos() {
        txtCodigoUsuario.setText("");
        txtNomeUsuario.setText("");
        txtEmailUsuario.setText("");
        txtSenhaUsuario.setText("");
    }
}
